markdown: kramdown
kramdown:
  footnote_backlink: '&#x21A9;&#xFE0E;'

collections:
    workshops:
        output: true
    tutorials:
        output: true
    lessons:
        output: true

collections_dir: collections
baseurl: /forge
